import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from "./component/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between bg-black">
          <div className="flex items-center gap-2">
            <a href="/">
              <img
                className="invert"
                src="/next.svg"
                alt="Next.js logo"
                width={180}
                height={38}
              />
            </a>
            <a href="/">
              <img src="/file.svg" alt="File icon" width={16} height={16} />
            </a>
          </div>
          <div className="flex items-center gap-2">
            <a href="/">
              <img
                className="invert"
                src="/globe.svg"
                alt="Globe icon"
                width={16}
                height={16}
              />
            </a>
            <a href="/">
              <img
                className="invert"
                src="/window.svg"
                alt="Window icon"
                width={16}
                height={16}
              />
            </a>
          </div>
        </nav>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
